In [22]:
from sklearn import datasets
from pybrain.datasets.classification import ClassificationDataSet
from pybrain.tools.shortcuts import buildNetwork
from pybrain.supervised.trainers import BackpropTrainer
from pybrain.structure.modules import SoftmaxLayer
from pybrain.utilities import percentError
import numpy as np

In [2]:
iris = datasets.load_iris()

In [3]:
x = iris.data
y = iris.target
dataset = ClassificationDataSet(4,1,nb_classes=3)

In [4]:
for i in range(len(x)):
    dataset.addSample(x[i],y[i])

In [5]:
train_data_temp, part_data_temp = dataset.splitWithProportion(0.6)
test_data_temp,val_data_temp = part_data_temp.splitWithProportion(0.5)

In [11]:
#Conversão de supervised data set para Classification
train_data = ClassificationDataSet(4,1,nb_classes=3)
#adicionar em train_data
for n in range(train_data_temp.getLength()):
    #Usamos a funçao .getSample para pegar valores de entrada e saida sem 0 entarda e 1 saida
    train_data.addSample(train_data_temp.getSample(n)[0], train_data_temp.getSample(n)[1])
#Realizar para os outros datasets
test_data = ClassificationDataSet(4,1,nb_classes=3)
for n in range(test_data_temp.getLength()):
    test_data.addSample(test_data_temp.getSample(n)[0], test_data_temp.getSample(n)[1])
    
val_data = ClassificationDataSet(4,1,nb_classes=3)
for n in range(val_data_temp.getLength()):
    val_data.addSample(val_data_temp.getSample(n)[0], val_data_temp.getSample(n)[1])

In [12]:
print('Antes do _convertToOneOfMany')
print(train_data['target'][:5])

Antes do _convertToOneOfMany
[[2]
 [0]
 [0]
 [1]
 [1]]


In [13]:
train_data._convertToOneOfMany()
test_data._convertToOneOfMany()
val_data._convertToOneOfMany()

print('Depois do _convertToOneOfMany')
print(train_data['target'][:5])

Depois do _convertToOneOfMany
[[0 0 1]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]]


In [16]:
#Criando redes Neurais
net = buildNetwork(train_data.indim,5,train_data.outdim)
#Crianado modelo de treino
trainer = BackpropTrainer(net,dataset= train_data, learningrate=0.01, momentum=0.1)

In [24]:
trainer.trainOnDataset(train_data, 100)
out = net.activateOnDataset(test_data).argmax(axis=1)
print('Erro de teste: %.2f%%' % percentError(out, test_data['class']))

Erro de teste: 6.67%


In [27]:
out = net.activateOnDataset(val_data).argmax(axis=1)
print('Erro de teste: %.2f%%' % percentError(out, val_data['class']))

Erro de teste: 0.00%
